<a href="https://colab.research.google.com/github/vcoelh/ML/blob/main/Softmax_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
#%matplotlib widget
from matplotlib.widgets import Slider
from lab_utils_common import dlc
from lab_utils_softmax import plt_softmax
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [34]:
# centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
# X_train, y_train = make_blobs(n_samples=2000, centers= centers, cluster_std= 1.0, random_state = 30)

# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [45]:
# from keras.utils.sidecar_evaluator import optimizer
# , sparse_categorical_crossentropy
# , sparse_categorical_crossentropy
# from keras.backend import binary_crossentropy
# model = Sequential(
#     [
#         tf.keras.layers.Dense(units = 25, activation = 'relu'),
#         tf.keras.layers.Dense(units = 15, activation = 'relu'),
#         tf.keras.layers.Dense(units = 10, activation = 'softmax')
#     ]
# )

# model.compile(
#     loss = tf.keras.losses.SparseCategoricalCrossentropy(),
#     optimizer = tf.keras.optimizers.Adam(0.001)
# )

# model.fit(X_train, y_train, epochs= 10)

model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_train,y_train,
    epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 1.2463
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.6238
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.3291
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1642
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1016
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0774
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0643
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0566
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0508
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0470


In [46]:
# p_nonpreferred = model.predict(X_train)
# print(p_nonpreferred[:2])
# print(f' the lowest: {np.min(p_nonpreferred)}, the biggest: {np.max(p_nonpreferred)}')

p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 1ms/step
[[2.60e-03 1.05e-02 9.49e-01 3.76e-02]
 [9.93e-01 6.92e-03 4.25e-05 6.07e-05]]
largest value 0.9999973 smallest value 2.9770453e-09


In [47]:
### preferred organization

# preferred_model = Sequential(
#     [
#         tf.keras.layers.Dense(units = 25, activation = 'relu'),
#         tf.keras.layers.Dense(units = 15, activation = 'relu'),
#         tf.keras.layers.Dense(units = 4, activation = 'linear')
#     ]
# )

# preferred_model.compile(
#     loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
#     optimizer = tf.keras.optimizers.Adam(0.001) 
# )

# preferred_model.fit(X_train, y_train, epochs =10 )

preferred_model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)
       

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 0.7373
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.3128
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1336
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0826
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0631
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0531
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0463
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0417
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0382
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0352


In [50]:
preferred_predict = preferred_model.predict(X_train)
print(preferred_predict[:2])
print(f'max : {np.max(preferred_predict)}, min: {np.min(preferred_predict)}')


63/63 [==============================] - 0s 2ms/step
[[-2.89 -2.18  3.5  -1.62]
 [ 4.23 -1.37 -5.55 -6.12]]
max : 11.389432907104492, min: -10.502457618713379


In [51]:
sm_preferred = tf.nn.softmax(preferred_predict).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.67e-03 3.39e-03 9.89e-01 5.90e-03]
 [9.96e-01 3.68e-03 5.66e-05 3.19e-05]]
largest value 0.99999994 smallest value 1.9255701e-09


In [52]:
for i in range(5):
  print(f'{preferred_predict[i]}, category: {np.argmax(p_preferred[i])}')

[-2.89 -2.18  3.5  -1.62], category: 2
[ 4.23 -1.37 -5.55 -6.12], category: 0
[ 2.82 -0.53 -4.2  -4.95], category: 0
[-2.05  3.53 -1.51 -2.67], category: 1
[-0.38 -4.49  4.68 -4.58], category: 2
